apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xfab
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mxgy-tenant/rhtap-demo-app/hacbs-test-project-xfab@sha256:99113365bd5590f98da5a72ed5cc6c793b1b78676030cc9afe2bc5f046f837b4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
